### ISSUE TITLE
null_technical_500_response() got an unexpected keyword argument 'status_code'

### ISSUE THREAD

**Issue by lucemia** [livingbio/django-template#24]
```python
Traceback (most recent call last):
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 76, in response_for_exception
    response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
TypeError: null_technical_500_response() got an unexpected keyword argument 'status_code'
Traceback (most recent call last):
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 76, in response_for_exception
    response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
TypeError: null_technical_500_response() got an unexpected keyword argument 'status_code'
Traceback (most recent call last):
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/home/davidchen/media-library/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 76, in response_for_exception
    response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
TypeError: null_technical_500_response() got an unexpected keyword argument 'status_code'
```

原因 `wsgi.py`

```python

# Wrap werkzeug debugger if DEBUG is on
from django.conf import settings
if settings.DEBUG:
    try:
        import django.views.debug
        import six
        from werkzeug.debug import DebuggedApplication

        def null_technical_500_response(request, exc_type, exc_value, tb):
            six.reraise(exc_type, exc_value, tb)

        django.views.debug.technical_500_response = null_technical_500_response
        application = DebuggedApplication(application, evalex=True)
    except ImportError:
        pass

```

**Comment by lucemia** [comment]
可以直接用 django extension 的 `python manage.py runserver_plus` 取代
https://django-extensions.readthedocs.io/en/latest/runserver_plus.html

那這樣 wsgi.py 的修改就可以移除掉
